In [2]:
import pandas as pd
import numpy as np

In [7]:
pew = pd.read_csv('/Users/eunha/Desktop/2019 빅데이터 청년인재/tidy-data-master/data/pew.txt', delimiter='\t')

In [8]:
pew

,religion,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k,$75-100k,$100-150k,>150k,Don't know/refused
0,Agnostic,27,34,60,81,76,137,122,109,84,96
1,Atheist,12,27,37,52,35,70,73,59,74,76
2,Buddhist,27,21,30,34,33,58,62,39,53,54
3,Catholic,418,617,732,670,638,1116,949,792,633,1489
4,Don’t know/refused,15,14,15,11,10,35,21,17,18,116
5,Evangelical Prot,575,869,1064,982,881,1486,949,723,414,1529
6,Hindu,1,9,7,9,11,34,47,48,54,37
7,Historically Black Prot,228,244,236,238,197,223,131,81,78,339
8,Jehovah's Witness,20,27,24,24,21,30,15,11,6,37
9,Jewish,19,19,25,25,30,95,69,87,151,162
10,Mainline Prot,289,495,619,655,651,1107,939,753,634,1328
11,Mormon,29,40,48,51,56,112,85,49,42,69
12,Muslim,6,7,9,10,9,23,16,8,6,22
13,Orthodox,13,17,23,32,32,47,38,42,46,73
14,Other Christian,9,7,11,13,13,14,18,14,12,18
15,Other Faiths,20,33,40,46,49,63,46,40,41,71
16,Other World Religions,5,2,3,4,2,7,3,4,4,8
17,Unaffiliated,217,299,374,365,341,528,407,321,258,597

일반적인 사람들은 이 표가 한 눈에 보이니까 좋아함.  
정말 자주 있는 실수.  
wideformat(wideform)이라고 함  
이걸 바꾸는 게 longform

In [10]:
# pew.melt(
#     id_vars=None, <- 고정시킬 것
#     value_vars=None, <- 지금 안 쓴다
#     var_name=None,
#     value_name='value',
#     col_level=None,
# )
# 지금 여기서는 데이터 몇 개 넣어야? 디폴트값 다 있으니까 안 넣어도 됨
pew.melt()
# 컬럼 = 그 값으로 다 만들어놓음

               variable                    value
0              religion                 Agnostic
1              religion                  Atheist
2              religion                 Buddhist
3              religion                 Catholic
4              religion       Don’t know/refused
5              religion         Evangelical Prot
6              religion                    Hindu
7              religion  Historically Black Prot
8              religion        Jehovah's Witness
9              religion                   Jewish
10             religion            Mainline Prot
11             religion                   Mormon
12             religion                   Muslim
13             religion                 Orthodox
14             religion          Other Christian
15             religion             Other Faiths
16             religion    Other World Religions
17             religion             Unaffiliated
18                <$10k                       27
19                <$10k                       12
20                <$10k                       27
21                <$10k                      418
22                <$10k                       15
23                <$10k                      575
24                <$10k                        1
25                <$10k                      228
26                <$10k                       20
27                <$10k                       19
28                <$10k                      289
29                <$10k                       29
..                  ...                      ...
168               >150k                       54
169               >150k                       78
170               >150k                        6
171               >150k                      151
172               >150k                      634
173               >150k                       42
174               >150k                        6
175               >150k                       46
176               >150k                       12
177               >150k                       41
178               >150k                        4
179               >150k                      258
180  Don't know/refused                       96
181  Don't know/refused                       76
182  Don't know/refused                       54
183  Don't know/refused                     1489
184  Don't know/refused                      116
185  Don't know/refused                     1529
186  Don't know/refused                       37
187  Don't know/refused                      339
188  Don't know/refused                       37
189  Don't know/refused                      162
190  Don't know/refused                     1328
191  Don't know/refused                       69
192  Don't know/refused                       22
193  Don't know/refused                       73
194  Don't know/refused                       18
195  Don't know/refused                       71
196  Don't know/refused                        8
197  Don't know/refused                      597

[198 rows x 2 columns]

In [11]:
pew.melt(['religion']) # 분석용으로 쓰는 데이터
# 와이드포맷은 사람이 보기 좋으라고 쓰는 것

                    religion            variable  value
0                   Agnostic               <$10k     27
1                    Atheist               <$10k     12
2                   Buddhist               <$10k     27
3                   Catholic               <$10k    418
4         Don’t know/refused               <$10k     15
5           Evangelical Prot               <$10k    575
6                      Hindu               <$10k      1
7    Historically Black Prot               <$10k    228
8          Jehovah's Witness               <$10k     20
9                     Jewish               <$10k     19
10             Mainline Prot               <$10k    289
11                    Mormon               <$10k     29
12                    Muslim               <$10k      6
13                  Orthodox               <$10k     13
14           Other Christian               <$10k      9
15              Other Faiths               <$10k     20
16     Other World Religions               <$10k      5
17              Unaffiliated               <$10k    217
18                  Agnostic             $10-20k     34
19                   Atheist             $10-20k     27
20                  Buddhist             $10-20k     21
21                  Catholic             $10-20k    617
22        Don’t know/refused             $10-20k     14
23          Evangelical Prot             $10-20k    869
24                     Hindu             $10-20k      9
25   Historically Black Prot             $10-20k    244
26         Jehovah's Witness             $10-20k     27
27                    Jewish             $10-20k     19
28             Mainline Prot             $10-20k    495
29                    Mormon             $10-20k     40
..                       ...                 ...    ...
150                    Hindu               >150k     54
151  Historically Black Prot               >150k     78
152        Jehovah's Witness               >150k      6
153                   Jewish               >150k    151
154            Mainline Prot               >150k    634
155                   Mormon               >150k     42
156                   Muslim               >150k      6
157                 Orthodox               >150k     46
158          Other Christian               >150k     12
159             Other Faiths               >150k     41
160    Other World Religions               >150k      4
161             Unaffiliated               >150k    258
162                 Agnostic  Don't know/refused     96
163                  Atheist  Don't know/refused     76
164                 Buddhist  Don't know/refused     54
165                 Catholic  Don't know/refused   1489
166       Don’t know/refused  Don't know/refused    116
167         Evangelical Prot  Don't know/refused   1529
168                    Hindu  Don't know/refused     37
169  Historically Black Prot  Don't know/refused    339
170        Jehovah's Witness  Don't know/refused     37
171                   Jewish  Don't know/refused    162
172            Mainline Prot  Don't know/refused   1328
173                   Mormon  Don't know/refused     69
174                   Muslim  Don't know/refused     22
175                 Orthodox  Don't know/refused     73
176          Other Christian  Don't know/refused     18
177             Other Faiths  Don't know/refused     71
178    Other World Religions  Don't know/refused      8
179             Unaffiliated  Don't know/refused    597

[180 rows x 3 columns]

In [12]:
pew.melt(['religion'], var_name = '문', value_name="근영") # rename써서 바꿔도 되는데 귀찮으니까 한번에 바꿈

                    religion                   문    근영
0                   Agnostic               <$10k    27
1                    Atheist               <$10k    12
2                   Buddhist               <$10k    27
3                   Catholic               <$10k   418
4         Don’t know/refused               <$10k    15
5           Evangelical Prot               <$10k   575
6                      Hindu               <$10k     1
7    Historically Black Prot               <$10k   228
8          Jehovah's Witness               <$10k    20
9                     Jewish               <$10k    19
10             Mainline Prot               <$10k   289
11                    Mormon               <$10k    29
12                    Muslim               <$10k     6
13                  Orthodox               <$10k    13
14           Other Christian               <$10k     9
15              Other Faiths               <$10k    20
16     Other World Religions               <$10k     5
17              Unaffiliated               <$10k   217
18                  Agnostic             $10-20k    34
19                   Atheist             $10-20k    27
20                  Buddhist             $10-20k    21
21                  Catholic             $10-20k   617
22        Don’t know/refused             $10-20k    14
23          Evangelical Prot             $10-20k   869
24                     Hindu             $10-20k     9
25   Historically Black Prot             $10-20k   244
26         Jehovah's Witness             $10-20k    27
27                    Jewish             $10-20k    19
28             Mainline Prot             $10-20k   495
29                    Mormon             $10-20k    40
..                       ...                 ...   ...
150                    Hindu               >150k    54
151  Historically Black Prot               >150k    78
152        Jehovah's Witness               >150k     6
153                   Jewish               >150k   151
154            Mainline Prot               >150k   634
155                   Mormon               >150k    42
156                   Muslim               >150k     6
157                 Orthodox               >150k    46
158          Other Christian               >150k    12
159             Other Faiths               >150k    41
160    Other World Religions               >150k     4
161             Unaffiliated               >150k   258
162                 Agnostic  Don't know/refused    96
163                  Atheist  Don't know/refused    76
164                 Buddhist  Don't know/refused    54
165                 Catholic  Don't know/refused  1489
166       Don’t know/refused  Don't know/refused   116
167         Evangelical Prot  Don't know/refused  1529
168                    Hindu  Don't know/refused    37
169  Historically Black Prot  Don't know/refused   339
170        Jehovah's Witness  Don't know/refused    37
171                   Jewish  Don't know/refused   162
172            Mainline Prot  Don't know/refused  1328
173                   Mormon  Don't know/refused    69
174                   Muslim  Don't know/refused    22
175                 Orthodox  Don't know/refused    73
176          Other Christian  Don't know/refused    18
177             Other Faiths  Don't know/refused    71
178    Other World Religions  Don't know/refused     8
179             Unaffiliated  Don't know/refused   597

[180 rows x 3 columns]

In [13]:
pew.melt(['religion']).variable.value_counts()

$30-40k               18
>150k                 18
Don't know/refused    18
$40-50k               18
$10-20k               18
$75-100k              18
<$10k                 18
$100-150k             18
$20-30k               18
$50-75k               18
Name: variable, dtype: int64

In [14]:
# 18?

In [15]:
pew = pew.melt(['religion']) # in..없으니까 재할당

In [16]:
pew.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 3 columns):
religion    180 non-null object
variable    180 non-null object
value       180 non-null int64
dtypes: int64(1), object(2)
memory usage: 4.3+ KB

In [17]:
pew

                    religion            variable  value
0                   Agnostic               <$10k     27
1                    Atheist               <$10k     12
2                   Buddhist               <$10k     27
3                   Catholic               <$10k    418
4         Don’t know/refused               <$10k     15
5           Evangelical Prot               <$10k    575
6                      Hindu               <$10k      1
7    Historically Black Prot               <$10k    228
8          Jehovah's Witness               <$10k     20
9                     Jewish               <$10k     19
10             Mainline Prot               <$10k    289
11                    Mormon               <$10k     29
12                    Muslim               <$10k      6
13                  Orthodox               <$10k     13
14           Other Christian               <$10k      9
15              Other Faiths               <$10k     20
16     Other World Religions               <$10k      5
17              Unaffiliated               <$10k    217
18                  Agnostic             $10-20k     34
19                   Atheist             $10-20k     27
20                  Buddhist             $10-20k     21
21                  Catholic             $10-20k    617
22        Don’t know/refused             $10-20k     14
23          Evangelical Prot             $10-20k    869
24                     Hindu             $10-20k      9
25   Historically Black Prot             $10-20k    244
26         Jehovah's Witness             $10-20k     27
27                    Jewish             $10-20k     19
28             Mainline Prot             $10-20k    495
29                    Mormon             $10-20k     40
..                       ...                 ...    ...
150                    Hindu               >150k     54
151  Historically Black Prot               >150k     78
152        Jehovah's Witness               >150k      6
153                   Jewish               >150k    151
154            Mainline Prot               >150k    634
155                   Mormon               >150k     42
156                   Muslim               >150k      6
157                 Orthodox               >150k     46
158          Other Christian               >150k     12
159             Other Faiths               >150k     41
160    Other World Religions               >150k      4
161             Unaffiliated               >150k    258
162                 Agnostic  Don't know/refused     96
163                  Atheist  Don't know/refused     76
164                 Buddhist  Don't know/refused     54
165                 Catholic  Don't know/refused   1489
166       Don’t know/refused  Don't know/refused    116
167         Evangelical Prot  Don't know/refused   1529
168                    Hindu  Don't know/refused     37
169  Historically Black Prot  Don't know/refused    339
170        Jehovah's Witness  Don't know/refused     37
171                   Jewish  Don't know/refused    162
172            Mainline Prot  Don't know/refused   1328
173                   Mormon  Don't know/refused     69
174                   Muslim  Don't know/refused     22
175                 Orthodox  Don't know/refused     73
176          Other Christian  Don't know/refused     18
177             Other Faiths  Don't know/refused     71
178    Other World Religions  Don't know/refused      8
179             Unaffiliated  Don't know/refused    597

[180 rows x 3 columns]

In [20]:
pew.describe() # 값이 어떻게 되는지 묶어서 알 수 있음 의미있는 값을 가지게 되었다

             value
count   180.000000
mean    197.533333
std     326.548693
min       1.000000
25%      18.000000
50%      46.000000
75%     218.500000
max    1529.000000

In [21]:
pew.groupby('variable').mean()

                         value
variable
$10-20k             154.500000
$100-150k           177.611111
$20-30k             186.500000
$30-40k             183.444444
$40-50k             171.388889
$50-75k             288.055556
$75-100k            221.666667
<$10k               107.222222
>150k               144.888889
Don't know/refused  340.055556

In [22]:
# longformat이 아니면 분석할 때 쓰는 포맷이 아니기 때문에 안 되는 게 너무 많다
# 이 때 쓰는 게 .melt()
# tidy data가 아니면 첫번째 해야 되는 것!
# R쪽에서는 아주 기본적으로 쓰는 것

In [32]:
weather = pd.read_csv('/Users/eunha/Desktop/2019 빅데이터 청년인재/tidy-data-master/data/weather.txt',
                      delimiter='\t', na_values='-')

In [33]:
weather

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
0,MX000017004,2010,1,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,278.0,NaN
1,MX000017004,2010,1,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,145.0,NaN
2,MX000017004,2010,2,TMAX,NaN,273.0,241.0,NaN,NaN,NaN,...,NaN,299.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MX000017004,2010,2,TMIN,NaN,144.0,144.0,NaN,NaN,NaN,...,NaN,107.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MX000017004,2010,3,TMAX,NaN,NaN,NaN,NaN,321.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,MX000017004,2010,3,TMIN,NaN,NaN,NaN,NaN,142.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MX000017004,2010,4,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,363.0,NaN,NaN,NaN,NaN
7,MX000017004,2010,4,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,167.0,NaN,NaN,NaN,NaN
8,MX000017004,2010,5,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,332.0,NaN,NaN,NaN,NaN
9,MX000017004,2010,5,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,182.0,NaN,NaN,NaN,NaN
10,MX000017004,2010,6,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301.0,NaN,NaN
11,MX000017004,2010,6,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.0,NaN,NaN
12,MX000017004,2010,7,TMAX,NaN,NaN,286.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,MX000017004,2010,7,TMIN,NaN,NaN,175.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,MX000017004,2010,8,TMAX,NaN,NaN,NaN,NaN,296.0,NaN,...,NaN,264.0,NaN,297.0,NaN,NaN,NaN,280.0,NaN,254.0
15,MX000017004,2010,8,TMIN,NaN,NaN,NaN,NaN,158.0,NaN,...,NaN,150.0,NaN,156.0,NaN,NaN,NaN,153.0,NaN,154.0
16,MX000017004,2010,10,TMAX,NaN,NaN,NaN,NaN,270.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,312.0,NaN,NaN,NaN
17,MX000017004,2010,10,TMIN,NaN,NaN,NaN,NaN,140.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,150.0,NaN,NaN,NaN
18,MX000017004,2010,11,TMAX,NaN,313.0,NaN,272.0,263.0,NaN,...,NaN,NaN,NaN,NaN,281.0,277.0,NaN,NaN,NaN,NaN
19,MX000017004,2010,11,TMIN,NaN,163.0,NaN,120.0,79.0,NaN,...,NaN,NaN,NaN,NaN,121.0,142.0,NaN,NaN,NaN,NaN
20,MX000017004,2010,12,TMAX,299.0,NaN,NaN,NaN,NaN,278.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MX000017004,2010,12,TMIN,138.0,NaN,NaN,NaN,NaN,105.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
weather = weather.melt(weather.columns[:4], var_name='day').dropna()
weather

              id  year  month element    day value
0    MX000017004  2010     12    TMAX    day    d1
1    MX000017004  2010     12    TMIN    day    d1
2    MX000017004  2010      2    TMAX    day    d2
3    MX000017004  2010      2    TMIN    day    d2
4    MX000017004  2010     11    TMAX    day    d2
5    MX000017004  2010     11    TMIN    day    d2
6    MX000017004  2010      2    TMAX    day    d3
7    MX000017004  2010      2    TMIN    day    d3
8    MX000017004  2010      7    TMAX    day    d3
9    MX000017004  2010      7    TMIN    day    d3
10   MX000017004  2010     11    TMAX    day    d4
11   MX000017004  2010     11    TMIN    day    d4
12   MX000017004  2010      3    TMAX    day    d5
13   MX000017004  2010      3    TMIN    day    d5
14   MX000017004  2010      8    TMAX    day    d5
15   MX000017004  2010      8    TMIN    day    d5
16   MX000017004  2010     10    TMAX    day    d5
17   MX000017004  2010     10    TMIN    day    d5
18   MX000017004  2010     11    TMAX    day    d5
19   MX000017004  2010     11    TMIN    day    d5
20   MX000017004  2010     12    TMAX    day    d6
21   MX000017004  2010     12    TMIN    day    d6
22   MX000017004  2010     10    TMAX    day    d7
23   MX000017004  2010     10    TMIN    day    d7
24   MX000017004  2010      8    TMAX    day    d8
25   MX000017004  2010      8    TMIN    day    d8
26   MX000017004  2010      3    TMAX    day   d10
27   MX000017004  2010      3    TMIN    day   d10
28   MX000017004  2010      2    TMAX    day   d11
29   MX000017004  2010      2    TMIN    day   d11
..           ...   ...    ...     ...    ...   ...
102  MX000017004  2010     10    TMAX  value   287
103  MX000017004  2010     10    TMIN  value   105
104  MX000017004  2010      3    TMAX  value   311
105  MX000017004  2010      3    TMIN  value   176
106  MX000017004  2010      6    TMAX  value   280
107  MX000017004  2010      6    TMIN  value   175
108  MX000017004  2010      2    TMAX  value   299
109  MX000017004  2010      2    TMIN  value   107
110  MX000017004  2010      8    TMAX  value   264
111  MX000017004  2010      8    TMIN  value   150
112  MX000017004  2010      8    TMAX  value   297
113  MX000017004  2010      8    TMIN  value   156
114  MX000017004  2010     11    TMAX  value   281
115  MX000017004  2010     11    TMIN  value   121
116  MX000017004  2010      4    TMAX  value   363
117  MX000017004  2010      4    TMIN  value   167
118  MX000017004  2010      5    TMAX  value   332
119  MX000017004  2010      5    TMIN  value   182
120  MX000017004  2010     11    TMAX  value   277
121  MX000017004  2010     11    TMIN  value   142
122  MX000017004  2010     10    TMAX  value   312
123  MX000017004  2010     10    TMIN  value   150
124  MX000017004  2010      6    TMAX  value   301
125  MX000017004  2010      6    TMIN  value   180
126  MX000017004  2010      8    TMAX  value   280
127  MX000017004  2010      8    TMIN  value   153
128  MX000017004  2010      1    TMAX  value   278
129  MX000017004  2010      1    TMIN  value   145
130  MX000017004  2010      8    TMAX  value   254
131  MX000017004  2010      8    TMIN  value   154

[132 rows x 6 columns]

In [40]:
weather.describe() # year 전부 2010 -> 의미없음

         year       month
count   132.0  132.000000
mean   2010.0    7.212121
std       0.0    3.404152
min    2010.0    1.000000
25%    2010.0    4.000000
50%    2010.0    8.000000
75%    2010.0   10.000000
max    2010.0   12.000000

In [46]:
weather.drop(columns=['id', 'year'], inplace=True)

KeyError: "['id' 'year'] not found in axis"

In [47]:
weather

     month element    day value
0       12    TMAX    day    d1
1       12    TMIN    day    d1
2        2    TMAX    day    d2
3        2    TMIN    day    d2
4       11    TMAX    day    d2
5       11    TMIN    day    d2
6        2    TMAX    day    d3
7        2    TMIN    day    d3
8        7    TMAX    day    d3
9        7    TMIN    day    d3
10      11    TMAX    day    d4
11      11    TMIN    day    d4
12       3    TMAX    day    d5
13       3    TMIN    day    d5
14       8    TMAX    day    d5
15       8    TMIN    day    d5
16      10    TMAX    day    d5
17      10    TMIN    day    d5
18      11    TMAX    day    d5
19      11    TMIN    day    d5
20      12    TMAX    day    d6
21      12    TMIN    day    d6
22      10    TMAX    day    d7
23      10    TMIN    day    d7
24       8    TMAX    day    d8
25       8    TMIN    day    d8
26       3    TMAX    day   d10
27       3    TMIN    day   d10
28       2    TMAX    day   d11
29       2    TMIN    day   d11
..     ...     ...    ...   ...
102     10    TMAX  value   287
103     10    TMIN  value   105
104      3    TMAX  value   311
105      3    TMIN  value   176
106      6    TMAX  value   280
107      6    TMIN  value   175
108      2    TMAX  value   299
109      2    TMIN  value   107
110      8    TMAX  value   264
111      8    TMIN  value   150
112      8    TMAX  value   297
113      8    TMIN  value   156
114     11    TMAX  value   281
115     11    TMIN  value   121
116      4    TMAX  value   363
117      4    TMIN  value   167
118      5    TMAX  value   332
119      5    TMIN  value   182
120     11    TMAX  value   277
121     11    TMIN  value   142
122     10    TMAX  value   312
123     10    TMIN  value   150
124      6    TMAX  value   301
125      6    TMIN  value   180
126      8    TMAX  value   280
127      8    TMIN  value   153
128      1    TMAX  value   278
129      1    TMIN  value   145
130      8    TMAX  value   254
131      8    TMIN  value   154

[132 rows x 4 columns]

In [48]:
weather.reset_index(drop=True, inplace=True)

In [49]:
weather

     month element    day value
0       12    TMAX    day    d1
1       12    TMIN    day    d1
2        2    TMAX    day    d2
3        2    TMIN    day    d2
4       11    TMAX    day    d2
5       11    TMIN    day    d2
6        2    TMAX    day    d3
7        2    TMIN    day    d3
8        7    TMAX    day    d3
9        7    TMIN    day    d3
10      11    TMAX    day    d4
11      11    TMIN    day    d4
12       3    TMAX    day    d5
13       3    TMIN    day    d5
14       8    TMAX    day    d5
15       8    TMIN    day    d5
16      10    TMAX    day    d5
17      10    TMIN    day    d5
18      11    TMAX    day    d5
19      11    TMIN    day    d5
20      12    TMAX    day    d6
21      12    TMIN    day    d6
22      10    TMAX    day    d7
23      10    TMIN    day    d7
24       8    TMAX    day    d8
25       8    TMIN    day    d8
26       3    TMAX    day   d10
27       3    TMIN    day   d10
28       2    TMAX    day   d11
29       2    TMIN    day   d11
..     ...     ...    ...   ...
102     10    TMAX  value   287
103     10    TMIN  value   105
104      3    TMAX  value   311
105      3    TMIN  value   176
106      6    TMAX  value   280
107      6    TMIN  value   175
108      2    TMAX  value   299
109      2    TMIN  value   107
110      8    TMAX  value   264
111      8    TMIN  value   150
112      8    TMAX  value   297
113      8    TMIN  value   156
114     11    TMAX  value   281
115     11    TMIN  value   121
116      4    TMAX  value   363
117      4    TMIN  value   167
118      5    TMAX  value   332
119      5    TMIN  value   182
120     11    TMAX  value   277
121     11    TMIN  value   142
122     10    TMAX  value   312
123     10    TMIN  value   150
124      6    TMAX  value   301
125      6    TMIN  value   180
126      8    TMAX  value   280
127      8    TMIN  value   153
128      1    TMAX  value   278
129      1    TMIN  value   145
130      8    TMAX  value   254
131      8    TMIN  value   154

[132 rows x 4 columns]

In [52]:
weather.value = weather.value.str.replace('d','')

In [53]:
weather

     month element    day value
0       12    TMAX    day     1
1       12    TMIN    day     1
2        2    TMAX    day     2
3        2    TMIN    day     2
4       11    TMAX    day     2
5       11    TMIN    day     2
6        2    TMAX    day     3
7        2    TMIN    day     3
8        7    TMAX    day     3
9        7    TMIN    day     3
10      11    TMAX    day     4
11      11    TMIN    day     4
12       3    TMAX    day     5
13       3    TMIN    day     5
14       8    TMAX    day     5
15       8    TMIN    day     5
16      10    TMAX    day     5
17      10    TMIN    day     5
18      11    TMAX    day     5
19      11    TMIN    day     5
20      12    TMAX    day     6
21      12    TMIN    day     6
22      10    TMAX    day     7
23      10    TMIN    day     7
24       8    TMAX    day     8
25       8    TMIN    day     8
26       3    TMAX    day    10
27       3    TMIN    day    10
28       2    TMAX    day    11
29       2    TMIN    day    11
..     ...     ...    ...   ...
102     10    TMAX  value   NaN
103     10    TMIN  value   NaN
104      3    TMAX  value   NaN
105      3    TMIN  value   NaN
106      6    TMAX  value   NaN
107      6    TMIN  value   NaN
108      2    TMAX  value   NaN
109      2    TMIN  value   NaN
110      8    TMAX  value   NaN
111      8    TMIN  value   NaN
112      8    TMAX  value   NaN
113      8    TMIN  value   NaN
114     11    TMAX  value   NaN
115     11    TMIN  value   NaN
116      4    TMAX  value   NaN
117      4    TMIN  value   NaN
118      5    TMAX  value   NaN
119      5    TMIN  value   NaN
120     11    TMAX  value   NaN
121     11    TMIN  value   NaN
122     10    TMAX  value   NaN
123     10    TMIN  value   NaN
124      6    TMAX  value   NaN
125      6    TMIN  value   NaN
126      8    TMAX  value   NaN
127      8    TMIN  value   NaN
128      1    TMAX  value   NaN
129      1    TMIN  value   NaN
130      8    TMAX  value   NaN
131      8    TMIN  value   NaN

[132 rows x 4 columns]

In [54]:
weather.drop(columns=['day'], inplace=True)

In [59]:
weather.sort_values('month', inplace=True)

In [60]:
weather.reset_index(drop=True, inplace=True)

In [61]:
weather

     month element value
0        1    TMIN   NaN
1        1    TMAX   NaN
2        1    TMIN    30
3        1    TMAX    30
4        2    TMAX     2
5        2    TMIN     2
6        2    TMAX   NaN
7        2    TMIN     3
8        2    TMIN   NaN
9        2    TMAX    11
10       2    TMIN    11
11       2    TMAX     3
12       2    TMIN   NaN
13       2    TMIN    23
14       2    TMAX    23
15       2    TMIN   NaN
16       2    TMIN   NaN
17       2    TMAX   NaN
18       2    TMAX   NaN
19       2    TMAX   NaN
20       3    TMIN    10
21       3    TMAX     5
22       3    TMAX    10
23       3    TMAX   NaN
24       3    TMAX   NaN
25       3    TMIN    16
26       3    TMIN   NaN
27       3    TMAX    16
28       3    TMAX   NaN
29       3    TMIN   NaN
..     ...     ...   ...
102     10    TMAX    14
103     10    TMAX   NaN
104     11    TMIN   NaN
105     11    TMAX    26
106     11    TMIN    26
107     11    TMAX    27
108     11    TMIN   NaN
109     11    TMIN     5
110     11    TMAX   NaN
111     11    TMIN    27
112     11    TMAX   NaN
113     11    TMIN   NaN
114     11    TMAX   NaN
115     11    TMIN     4
116     11    TMAX   NaN
117     11    TMIN   NaN
118     11    TMAX     5
119     11    TMIN   NaN
120     11    TMAX     4
121     11    TMIN     2
122     11    TMAX     2
123     11    TMAX   NaN
124     12    TMIN     6
125     12    TMIN   NaN
126     12    TMIN   NaN
127     12    TMAX   NaN
128     12    TMAX   NaN
129     12    TMIN     1
130     12    TMAX     6
131     12    TMAX     1

[132 rows x 3 columns]

In [66]:
weather = pd.read_csv('/Users/eunha/Desktop/2019 빅데이터 청년인재/tidy-data-master/data/weather.txt',
                      sep='\t')

In [67]:
weather

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
0,MX000017004,2010,1,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,278.0,NaN
1,MX000017004,2010,1,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,145.0,NaN
2,MX000017004,2010,2,TMAX,NaN,273.0,241.0,NaN,NaN,NaN,...,NaN,299.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MX000017004,2010,2,TMIN,NaN,144.0,144.0,NaN,NaN,NaN,...,NaN,107.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MX000017004,2010,3,TMAX,NaN,NaN,NaN,NaN,321.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,MX000017004,2010,3,TMIN,NaN,NaN,NaN,NaN,142.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MX000017004,2010,4,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,363.0,NaN,NaN,NaN,NaN
7,MX000017004,2010,4,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,167.0,NaN,NaN,NaN,NaN
8,MX000017004,2010,5,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,332.0,NaN,NaN,NaN,NaN
9,MX000017004,2010,5,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,182.0,NaN,NaN,NaN,NaN
10,MX000017004,2010,6,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301.0,NaN,NaN
11,MX000017004,2010,6,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.0,NaN,NaN
12,MX000017004,2010,7,TMAX,NaN,NaN,286.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,MX000017004,2010,7,TMIN,NaN,NaN,175.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,MX000017004,2010,8,TMAX,NaN,NaN,NaN,NaN,296.0,NaN,...,NaN,264.0,NaN,297.0,NaN,NaN,NaN,280.0,NaN,254.0
15,MX000017004,2010,8,TMIN,NaN,NaN,NaN,NaN,158.0,NaN,...,NaN,150.0,NaN,156.0,NaN,NaN,NaN,153.0,NaN,154.0
16,MX000017004,2010,10,TMAX,NaN,NaN,NaN,NaN,270.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,312.0,NaN,NaN,NaN
17,MX000017004,2010,10,TMIN,NaN,NaN,NaN,NaN,140.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,150.0,NaN,NaN,NaN
18,MX000017004,2010,11,TMAX,NaN,313.0,NaN,272.0,263.0,NaN,...,NaN,NaN,NaN,NaN,281.0,277.0,NaN,NaN,NaN,NaN
19,MX000017004,2010,11,TMIN,NaN,163.0,NaN,120.0,79.0,NaN,...,NaN,NaN,NaN,NaN,121.0,142.0,NaN,NaN,NaN,NaN
20,MX000017004,2010,12,TMAX,299.0,NaN,NaN,NaN,NaN,278.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MX000017004,2010,12,TMIN,138.0,NaN,NaN,NaN,NaN,105.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
pd.wide_to_long(weather, 'd', ['id', 'year', 'month', 'element'], '')

                                       d
id          year month element
MX000017004 2010 1     TMAX    1     NaN
                               2     NaN
                               3     NaN
                               4     NaN
                               5     NaN
                               6     NaN
                               7     NaN
                               8     NaN
                               9     NaN
                               10    NaN
                               11    NaN
                               12    NaN
                               13    NaN
                               14    NaN
                               15    NaN
                               16    NaN
                               17    NaN
                               18    NaN
                               19    NaN
                               20    NaN
                               21    NaN
                               22    NaN
                               23    NaN
                               24    NaN
                               25    NaN
                               26    NaN
                               27    NaN
                               28    NaN
                               29    NaN
                               30  278.0
...                                  ...
                 12    TMIN    2     NaN
                               3     NaN
                               4     NaN
                               5     NaN
                               6   105.0
                               7     NaN
                               8     NaN
                               9     NaN
                               10    NaN
                               11    NaN
                               12    NaN
                               13    NaN
                               14    NaN
                               15    NaN
                               16    NaN
                               17    NaN
                               18    NaN
                               19    NaN
                               20    NaN
                               21    NaN
                               22    NaN
                               23    NaN
                               24    NaN
                               25    NaN
                               26    NaN
                               27    NaN
                               28    NaN
                               29    NaN
                               30    NaN
                               31    NaN

[682 rows x 1 columns]

In [69]:
pd.wide_to_long(weather, 'd', ['id', 'year', 'month', 'element'], '').dropna()
# 멀티인덱스
# 공통된 것을 모두 그룹화해줘서 보기가 좀더 편함
# melt보다 조금더 편하고 예쁘게 지원
# 그래서 판다스에는 두가지 방식의 melt

                                       d
id          year month element
MX000017004 2010 1     TMAX    30  278.0
                       TMIN    30  145.0
                 2     TMAX    2   273.0
                               3   241.0
                               11  297.0
                               23  299.0
                       TMIN    2   144.0
                               3   144.0
                               11  134.0
                               23  107.0
                 3     TMAX    5   321.0
                               10  345.0
                               16  311.0
                       TMIN    5   142.0
                               10  168.0
                               16  176.0
                 4     TMAX    27  363.0
                       TMIN    27  167.0
                 5     TMAX    27  332.0
                       TMIN    27  182.0
                 6     TMAX    17  280.0
                               29  301.0
                       TMIN    17  175.0
                               29  180.0
                 7     TMAX    3   286.0
                               14  299.0
                       TMIN    3   175.0
                               14  165.0
                 8     TMAX    5   296.0
                               8   290.0
...                                  ...
                       TMIN    8   173.0
                               13  165.0
                               23  150.0
                               25  156.0
                               29  153.0
                               31  154.0
                 10    TMAX    5   270.0
                               7   281.0
                               14  295.0
                               15  287.0
                               28  312.0
                       TMIN    5   140.0
                               7   129.0
                               14  130.0
                               15  105.0
                               28  150.0
                 11    TMAX    2   313.0
                               4   272.0
                               5   263.0
                               26  281.0
                               27  277.0
                       TMIN    2   163.0
                               4   120.0
                               5    79.0
                               26  121.0
                               27  142.0
                 12    TMAX    1   299.0
                               6   278.0
                       TMIN    1   138.0
                               6   105.0

[66 rows x 1 columns]

In [64]:
billboard = pd.read_csv('/Users/eunha/Desktop/2019 빅데이터 청년인재/tidy-data-master/data/billboard.csv',)

In [65]:
billboard

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2000,Janet,Doesn't Really Matter,4:17,Rock,2000-06-17,2000-08-26,59,52.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2000,Destiny's Child,Say My Name,4:31,Rock,1999-12-25,2000-03-18,83,83.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2000,"Iglesias, Enrique",Be With You,3:36,Latin,2000-04-01,2000-06-24,63,45.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2000,Sisqo,Incomplete,3:52,Rock,2000-06-24,2000-08-12,77,66.0,61.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,81,54.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2000,N'Sync,It's Gonna Be Me,3:10,Rock,2000-05-06,2000-07-29,82,70.0,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2000,"Aguilera, Christina",What A Girl Wants,3:18,Rock,1999-11-27,2000-01-15,71,51.0,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2000,Vertical Horizon,Everything You Want,4:01,Rock,2000-01-22,2000-07-15,70,61.0,53.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2000,Creed,With Arms Wide Open,3:52,Rock,2000-05-13,2000-11-11,84,78.0,76.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2000,Aaliyah,Try Again,4:03,Rock,2000-03-18,2000-06-17,59,53.0,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2000,matchbox twenty,Bent,4:12,Rock,2000-04-29,2000-07-22,60,37.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2000,"Carey, Mariah",Thank God I Found You,4:14,Rock,1999-12-11,2000-02-19,82,68.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2000,"Hill, Faith",Breathe,4:04,Rap,1999-11-06,2000-04-22,81,68.0,62.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2000,Mya,Case Of The Ex (Whatcha Gonna Do),3:50,Rock,2000-08-19,2000-12-02,72,57.0,52.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2000,Dream,He Loves U Not,3:43,Rock,2000-09-30,2000-12-30,99,92.0,81.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2000,"Braxton, Toni",He Wasn't Man Enough,4:21,Rock,2000-03-18,2000-05-06,63,55.0,48.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2000,"Anthony, Marc",You Sang To Me,3:50,Latin,2000-02-26,2000-06-03,77,54.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2000,98�,Give Me Just One Night (Una Noche),3:24,Rock,2000-08-19,2000-09-30,51,39.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2000,Destiny's Child,Jumpin' Jumpin',3:48,Rock,2000-05-13,2000-08-19,74,71.0,65.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2000,3 Doors Down,Kryptonite,3:53,Rock,2000-04-08,2000-11-11,81,70.0,68.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2000,Sisqo,Thong Song,4:05,Rock,2000-01-29,2000-05-20,74,63.0,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2000,"Aguilera, Christina",I Turn To You,4:00,Rock,2000-04-15,2000-07-01,50,39.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2000,"Houston, Whitney",My Love Is Your Love,4:16,Rock,1999-09-04,2000-01-08,81,68.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2000,Joe,I Wanna Know,4:57,Rock,2000-01-01,2000-07-01,94,86.0,69.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2000,"Jordan, Montell",Get It On.. Tonite,4:34,Rap,1999-10-23,2000-02-12,92,80.0,72.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,2000-09-02,2000-09-09,91,87.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,2000,Madison Avenue,Don't Call Me Baby,3:44,Electronica,2000-07-08,2000-09-16,98,96.0,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,2000,Eve,Got It All,3:48,Rap,2000-07-15,2000-07-22,89,88.0,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,2000,Limp Bizkit,Re-Arranged,4:08,Rock,1999-12-04,2000-02-05,91,91.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,2000,"Spencer, Tracie",Still In My Heart,4:11,Rock,2000-03-04,2000-03-11,95,88.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,2000,Nu Flavor,3 Little Words,3:54,R&B,2000-06-03,2000-06-17,97,97.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,2000,Tamar,If You Don't Wanna Love Me,4:02,Rock,2000-03-25,2000-04-15,98,98.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,2000,"Levert, Gerald",Baby U Are,4:10,R&B,2000-08-19,2000-08-26,96,89.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,2000,"Hart, Beth",L.A. Song,3:47,Country,1999-11-27,2000-01-15,99,100.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296,2000,"Diffie, Joe",The Quittin' Kind,3:23,Country,2000-01-01,2000-01-22,98,100.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,2000,Funkmaster Flex,Do You,4:14,Rap,2000-11-11,2000-12-02,92,92.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,2000,"Price, Kelly",Love Sets You Free,3:46,Rock,2000-05-13,2000-05-20,92,91.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,2000,En Vogue,Riddle,5:10,Rock,2000-06-17,2000-06-17,92,92.0,97.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,2000,"Herndon, Ty",No Mercy,4:43,Country,2000-03-18,2000-05-06,100,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,2000,Anastacia,I'm Outta Love,4:01,Pop,2000-04-01,2000-04-01,92,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,2000,Trina,Pull Over,2:58,Rap,2000-09-09,2000-09-16,97,93.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,2000,Lil' Mo,Ta Da,4:17,Rap,2000-08-12,2000-09-16,100,99.0,97.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
304,2000,A*Teens,Dancing Queen,3:44,Pop,2000-07-08,2000-07-29,97,97.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,2000,"Sheist, Shade",Where I Wanna Be,4:16,Rap,2000-11-11,2000-11-18,96,95.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,2000,De La Soul,All Good?,5:02,Rap,2000-12-23,2000-12-23,96,96.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,2000,"Larrieux, Amel",Get Up,4:02,R&B,2000-03-04,2000-03-11,100,97.0,97.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,2000,"Braxton, Toni",Spanish Guitar,4:24,Rock,2000-12-02,2000-12-02,98,98.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,2000,Tuesday,I Know,4:06,Rock,2000-12-30,2000-12-30,98,98.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,2000,LL Cool J,Imagine That,4:00,Rap,2000-08-12,2000-08-19,99,98.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,2000,Master P,Souljas,3:33,Rap,2000-11-18,2000-11-18,98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,2000,Ghostface Killah,Cherchez LaGhost,3:04,R&B,2000-08-05,2000-08-05,98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Smith, Will",Freakin' It,3:58,Rap,2000-02-12,2000-02-12,99,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,Fragma,Toca's Miracle,3:22,R&B,2000-10-28,2000-10-28,99,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
billboard = pd.read_csv('/Users/eunha/Desktop/2019 빅데이터 청년인재/tidy-data-master/data/billboard.csv', 
                        parse_dates=True, date_parser='-') # <-??

In [74]:
billboard.info() #date.entered, date.peaked 날짜로 바꿔야 됨
# parse_dates 실패했음 -> 어쩔 수 없이 datetime 써서 바꿔야 함

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 317 entries, 0 to 316
Data columns (total 83 columns):
year               317 non-null int64
artist.inverted    317 non-null object
track              317 non-null object
time               317 non-null object
genre              317 non-null object
date.entered       317 non-null object
date.peaked        317 non-null object
x1st.week          317 non-null int64
x2nd.week          312 non-null float64
x3rd.week          307 non-null float64
x4th.week          300 non-null float64
x5th.week          292 non-null float64
x6th.week          280 non-null float64
x7th.week          269 non-null float64
x8th.week          260 non-null float64
x9th.week          253 non-null float64
x10th.week         244 non-null float64
x11th.week         236 non-null float64
x12th.week         222 non-null float64
x13th.week         210 non-null float64
x14th.week         204 non-null float64
x15th.week         197 non-null float64
x16th.week         182 non-null float64
x17th.week         177 non-null float64
x18th.week         166 non-null float64
x19th.week         156 non-null float64
x20th.week         146 non-null float64
x21st.week         65 non-null float64
x22nd.week         55 non-null float64
x23rd.week         48 non-null float64
x24th.week         46 non-null float64
x25th.week         38 non-null float64
x26th.week         36 non-null float64
x27th.week         29 non-null float64
x28th.week         24 non-null float64
x29th.week         20 non-null float64
x30th.week         20 non-null float64
x31st.week         19 non-null float64
x32nd.week         18 non-null float64
x33rd.week         12 non-null float64
x34th.week         10 non-null float64
x35th.week         9 non-null float64
x36th.week         9 non-null float64
x37th.week         9 non-null float64
x38th.week         8 non-null float64
x39th.week         8 non-null float64
x40th.week         7 non-null float64
x41st.week         7 non-null float64
x42nd.week         6 non-null float64
x43rd.week         6 non-null float64
x44th.week         6 non-null float64
x45th.week         5 non-null float64
x46th.week         5 non-null float64
x47th.week         5 non-null float64
x48th.week         4 non-null float64
x49th.week         4 non-null float64
x50th.week         4 non-null float64
x51st.week         4 non-null float64
x52nd.week         4 non-null float64
x53rd.week         4 non-null float64
x54th.week         2 non-null float64
x55th.week         2 non-null float64
x56th.week         2 non-null float64
x57th.week         2 non-null float64
x58th.week         2 non-null float64
x59th.week         2 non-null float64
x60th.week         2 non-null float64
x61st.week         2 non-null float64
x62nd.week         2 non-null float64
x63rd.week         2 non-null float64
x64th.week         2 non-null float64
x65th.week         1 non-null float64
x66th.week         0 non-null float64
x67th.week         0 non-null float64
x68th.week         0 non-null float64
x69th.week         0 non-null float64
x70th.week         0 non-null float64
x71st.week         0 non-null float64
x72nd.week         0 non-null float64
x73rd.week         0 non-null float64
x74th.week         0 non-null float64
x75th.week         0 non-null float64
x76th.week         0 non-null float64
dtypes: float64(75), int64(2), object(6)
memory usage: 205.6+ KB

In [75]:
billboard

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2000,Janet,Doesn't Really Matter,4:17,Rock,2000-06-17,2000-08-26,59,52.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2000,Destiny's Child,Say My Name,4:31,Rock,1999-12-25,2000-03-18,83,83.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2000,"Iglesias, Enrique",Be With You,3:36,Latin,2000-04-01,2000-06-24,63,45.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2000,Sisqo,Incomplete,3:52,Rock,2000-06-24,2000-08-12,77,66.0,61.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,81,54.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2000,N'Sync,It's Gonna Be Me,3:10,Rock,2000-05-06,2000-07-29,82,70.0,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2000,"Aguilera, Christina",What A Girl Wants,3:18,Rock,1999-11-27,2000-01-15,71,51.0,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2000,Vertical Horizon,Everything You Want,4:01,Rock,2000-01-22,2000-07-15,70,61.0,53.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2000,Creed,With Arms Wide Open,3:52,Rock,2000-05-13,2000-11-11,84,78.0,76.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2000,Aaliyah,Try Again,4:03,Rock,2000-03-18,2000-06-17,59,53.0,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2000,matchbox twenty,Bent,4:12,Rock,2000-04-29,2000-07-22,60,37.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2000,"Carey, Mariah",Thank God I Found You,4:14,Rock,1999-12-11,2000-02-19,82,68.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2000,"Hill, Faith",Breathe,4:04,Rap,1999-11-06,2000-04-22,81,68.0,62.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2000,Mya,Case Of The Ex (Whatcha Gonna Do),3:50,Rock,2000-08-19,2000-12-02,72,57.0,52.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2000,Dream,He Loves U Not,3:43,Rock,2000-09-30,2000-12-30,99,92.0,81.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2000,"Braxton, Toni",He Wasn't Man Enough,4:21,Rock,2000-03-18,2000-05-06,63,55.0,48.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2000,"Anthony, Marc",You Sang To Me,3:50,Latin,2000-02-26,2000-06-03,77,54.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2000,98�,Give Me Just One Night (Una Noche),3:24,Rock,2000-08-19,2000-09-30,51,39.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2000,Destiny's Child,Jumpin' Jumpin',3:48,Rock,2000-05-13,2000-08-19,74,71.0,65.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2000,3 Doors Down,Kryptonite,3:53,Rock,2000-04-08,2000-11-11,81,70.0,68.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2000,Sisqo,Thong Song,4:05,Rock,2000-01-29,2000-05-20,74,63.0,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2000,"Aguilera, Christina",I Turn To You,4:00,Rock,2000-04-15,2000-07-01,50,39.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2000,"Houston, Whitney",My Love Is Your Love,4:16,Rock,1999-09-04,2000-01-08,81,68.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2000,Joe,I Wanna Know,4:57,Rock,2000-01-01,2000-07-01,94,86.0,69.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2000,"Jordan, Montell",Get It On.. Tonite,4:34,Rap,1999-10-23,2000-02-12,92,80.0,72.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,2000-09-02,2000-09-09,91,87.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,2000,Madison Avenue,Don't Call Me Baby,3:44,Electronica,2000-07-08,2000-09-16,98,96.0,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,2000,Eve,Got It All,3:48,Rap,2000-07-15,2000-07-22,89,88.0,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,2000,Limp Bizkit,Re-Arranged,4:08,Rock,1999-12-04,2000-02-05,91,91.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,2000,"Spencer, Tracie",Still In My Heart,4:11,Rock,2000-03-04,2000-03-11,95,88.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,2000,Nu Flavor,3 Little Words,3:54,R&B,2000-06-03,2000-06-17,97,97.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,2000,Tamar,If You Don't Wanna Love Me,4:02,Rock,2000-03-25,2000-04-15,98,98.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,2000,"Levert, Gerald",Baby U Are,4:10,R&B,2000-08-19,2000-08-26,96,89.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,2000,"Hart, Beth",L.A. Song,3:47,Country,1999-11-27,2000-01-15,99,100.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296,2000,"Diffie, Joe",The Quittin' Kind,3:23,Country,2000-01-01,2000-01-22,98,100.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,2000,Funkmaster Flex,Do You,4:14,Rap,2000-11-11,2000-12-02,92,92.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,2000,"Price, Kelly",Love Sets You Free,3:46,Rock,2000-05-13,2000-05-20,92,91.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,2000,En Vogue,Riddle,5:10,Rock,2000-06-17,2000-06-17,92,92.0,97.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,2000,"Herndon, Ty",No Mercy,4:43,Country,2000-03-18,2000-05-06,100,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,2000,Anastacia,I'm Outta Love,4:01,Pop,2000-04-01,2000-04-01,92,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,2000,Trina,Pull Over,2:58,Rap,2000-09-09,2000-09-16,97,93.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,2000,Lil' Mo,Ta Da,4:17,Rap,2000-08-12,2000-09-16,100,99.0,97.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
304,2000,A*Teens,Dancing Queen,3:44,Pop,2000-07-08,2000-07-29,97,97.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,2000,"Sheist, Shade",Where I Wanna Be,4:16,Rap,2000-11-11,2000-11-18,96,95.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,2000,De La Soul,All Good?,5:02,Rap,2000-12-23,2000-12-23,96,96.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,2000,"Larrieux, Amel",Get Up,4:02,R&B,2000-03-04,2000-03-11,100,97.0,97.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,2000,"Braxton, Toni",Spanish Guitar,4:24,Rock,2000-12-02,2000-12-02,98,98.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,2000,Tuesday,I Know,4:06,Rock,2000-12-30,2000-12-30,98,98.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,2000,LL Cool J,Imagine That,4:00,Rap,2000-08-12,2000-08-19,99,98.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,2000,Master P,Souljas,3:33,Rap,2000-11-18,2000-11-18,98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,2000,Ghostface Killah,Cherchez LaGhost,3:04,R&B,2000-08-05,2000-08-05,98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Smith, Will",Freakin' It,3:58,Rap,2000-02-12,2000-02-12,99,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,Fragma,Toca's Miracle,3:22,R&B,2000-10-28,2000-10-28,99,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# billboard.melt()
# melt 자주 쓰이기 때문에 판다스에서

# Signature: pd.wide_to_long(df, stubnames, i, j, sep='', suffix='\\d+')
# Docstring:
# Wide panel to long format. Less flexible but more user-friendly than melt.

# With stubnames ['A', 'B'], this function expects to find one or more
# group of columns with format
# A-suffix1, A-suffix2,..., B-suffix1, B-suffix2,...
# You specify what you want to call this suffix in the resulting long format
# with `j` (for example `j='year'`)

# Each row of these wide variables are assumed to be uniquely identified by
# `i` (can be a single column name or a list of column names)

# All remaining variables in the data frame are left intact.

# pd.wide_to_long(billboard, ) # 얘를 만들어줌